# Linear Algebra / NumPy Review

Before we learn about how we can apply neural networks to predict breast cancer, we should review the necessary linear algebra. This notebook will teach you how to use NumPy for basic linear algrebra and data manipulations. First, import the required modules:

In [2]:
import numpy as np
import math

## NumPy Warmup

We can use np.array to represent matrices in NumPy as follows:

In [27]:
mat = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


This is a 3x5 matrix. How can we get only the first two rows of this matrix? Use NumPy's slice syntax to print out only the first two rows.

In [25]:
print(mat[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


How can we produce a 3x3 matrix that gets the first 3 elements of each row from mat? Use NumPy's slice syntax to reproduce the output shown.

In [28]:
print(mat[:, :3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Challenge: How can we produce a 3x2 matrix for which each row contains just the 1st and 3rd elements of the original matrix? Use NumPy's advanced slice syntax to reproduce the output shown.

In [32]:
print(mat[:, [0, 2]])

[[ 1  3]
 [ 6  8]
 [11 13]]


## Matrix Multiplication

The key operation a neural network does on its input is a series of matrix multiplications. For fully-connected neural networks like the ones we will be working with today, these matrix multiplications are just matrix-vector products.

That is, an input vector is multiplied by a matrix (representing the weights of the neural network) to produce another vector, and this vector is multiplied by another matrix to produce another vector, and this continues until the final vector, which is the output of the neural network. Here's an example of matrix-vector multiplication using NumPy:

In [35]:
input_vector = np.array([1, 2, 3])
weights_matrix = np.array([[1, -4, 5], [-7, 2, 2], [3, -5, 1]])


print("Input:", input_vector, "\n")
print("Weights:\n", weights_matrix, "\n")

result = np.matmul(input_vector, weights_matrix)

print("Result:", result)

Input: [1 2 3] 

Weights:
 [[ 1 -4  5]
 [-7  2  2]
 [ 3 -5  1]] 

Result: [ -4 -15  12]


This is a simplified neural network that takes in an input of size 1x3 and outputs one of size 1x3. What happens if we change the dimension of the weights matrix to 3x2? Try changing the above code so it produces the below output. Hint: use slicing to produce a new weights_matrix.

In [34]:
input_vector = np.array([1, 2, 3])
sliced_weights_matrix = weights_matrix[:, :2]


print("Input:", input_vector, "\n")
print("Weights:\n", sliced_weights_matrix, "\n")

result = np.matmul(input_vector, sliced_weights_matrix)

print("Result:", result)

print(np.array([[1, 2, 3], [4, 5, 6]]).shape)

Input: [1 2 3] 

Weights:
 [[ 1 -4]
 [-7  2]
 [ 3 -5]] 

Result: [ -4 -15]
(2, 3)


We changed the shape of the outputs! This is because we did matrix multiplication using 1x3 and 3x2 matrices, which gives us a resulting matrix of size 1x2. Manipulating the shape of our weight matrices is how we will change the number of neurons in each layer of our neural network.